using LMS.Data;using LMS.Models;using LMS.ViewModels;using Microsoft.AspNetCore.Mvc;using Microsoft.AspNetCore.Mvc.Rendering;using Microsoft.EntityFrameworkCore;
namespace LMS.Controllers;
public class IssuesController(ApplicationDbContext db):Controller
{
 public async Task<IActionResult> Index(string filter="All"){IQueryable<BookIssue> q=db.BookIssues.AsNoTracking().Include(x=>x.Book).Include(x=>x.Member).Include(x=>x.BookReturn);var today=DateTime.Today;q=filter switch{"Issued"=>q.Where(x=>x.Status=="Issued"),"Returned"=>q.Where(x=>x.Status=="Returned"),"Overdue"=>q.Where(x=>x.Status=="Issued"&&x.DueDate<today),_=>q};ViewBag.Filter=filter;return View(await q.OrderByDescending(x=>x.IssueDate).ToListAsync());}
 public async Task<IActionResult> Create(){var vm=new IssueBookViewModel();await Lists(vm);return View(vm);}
 [HttpPost,ValidateAntiForgeryToken]public async Task<IActionResult>Create(IssueBookViewModel vm){var member=vm.MemberId.HasValue?await db.Members.FindAsync(vm.MemberId.Value):null;var book=vm.BookId.HasValue?await db.Books.FindAsync(vm.BookId.Value):null;if(member is null||!member.IsActive)ModelState.AddModelError(nameof(vm.MemberId),"Select an active member.");if(book is null||book.AvailableQuantity<1)ModelState.AddModelError(nameof(vm.BookId),"Select an available book.");if(!ModelState.IsValid){await Lists(vm);return View(vm);}await using var transaction=await db.Database.BeginTransactionAsync();db.BookIssues.Add(new(){BookId=book!.Id,MemberId=member!.Id,IssueDate=vm.IssueDate.Date,DueDate=vm.DueDate.Date,Status="Issued"});book.AvailableQuantity--;await db.SaveChangesAsync();await transaction.CommitAsync();TempData["Success"]="Book issued successfully.";return RedirectToAction(nameof(Index));}
 private async Task Lists(IssueBookViewModel vm){vm.Members=await db.Members.AsNoTracking().Where(x=>x.IsActive).OrderBy(x=>x.Name).Select(x=>new SelectListItem(x.MemberCode+" - "+x.Name,x.Id.ToString())).ToListAsync();vm.Books=await db.Books.AsNoTracking().Where(x=>x.AvailableQuantity>0).OrderBy(x=>x.Title).Select(x=>new SelectListItem(x.Title+" ("+x.AvailableQuantity+" available)",x.Id.ToString())).ToListAsync();}
}
